---
- hosts: all
  become: true
  tasks:
    - name: Update repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Update repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"


- hosts: Controller
  become: true
  roles:
    - Controller

- hosts: Compute
  become: true
  roles:
    - Compute
